create extension if not exists "pg_cron" with schema "pg_catalog";

drop extension if exists "pg_net";


  create table "public"."appointments" (
    "id" uuid not null default gen_random_uuid(),
    "professional_id" uuid,
    "service_id" uuid,
    "client_id" uuid,
    "start_time" timestamp with time zone not null,
    "end_time" timestamp with time zone not null,
    "status" text default 'confirmed'::text,
    "notes" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "cancellation_token" text,
    "review_token" text,
    "google_calendar_event_id" text
      );


alter table "public"."appointments" enable row level security;


  create table "public"."availability" (
    "id" uuid not null default gen_random_uuid(),
    "professional_id" uuid not null,
    "day_of_week" integer not null,
    "is_available" boolean default true,
    "advance_hours" integer default 2,
    "created_at" timestamp with time zone default now(),
    "break_minutes" integer default 0,
    "cancel_hours" integer default 1,
    "time_blocks" jsonb not null
      );


alter table "public"."availability" enable row level security;


  create table "public"."clients" (
    "id" uuid not null default gen_random_uuid(),
    "name" text not null,
    "email" text not null,
    "phone" text not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."clients" enable row level security;


  create table "public"."p_activo" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "num" numeric
      );


alter table "public"."p_activo" enable row level security;


  create table "public"."professionals" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "name" text not null,
    "slug" text not null,
    "email" text not null,
    "rut" text not null,
    "phone" text,
    "bio" text,
    "social_links" jsonb default '{}'::jsonb,
    "carrusel_images" jsonb default '[]'::jsonb,
    "location" text,
    "map_embed_url" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "profile_image" text,
    "google_refresh_token" text,
    "hide_reviews" boolean default false,
    "is_approved" boolean default false,
    "google_calendar_id" text
      );


alter table "public"."professionals" enable row level security;


  create table "public"."reviews" (
    "id" uuid not null default gen_random_uuid(),
    "appointment_id" uuid not null,
    "professional_id" uuid not null,
    "client_name" text not null,
    "rating" integer not null,
    "comment" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."reviews" enable row level security;


  create table "public"."services" (
    "id" uuid not null default gen_random_uuid(),
    "professional_id" uuid,
    "name" text not null,
    "description" text,
    "duration_minutes" integer not null,
    "price" numeric(10,2) not null,
    "is_active" boolean default true,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now(),
    "image_url" text default ''::text
      );


alter table "public"."services" enable row level security;


  create table "public"."unavailable_dates" (
    "id" uuid not null default gen_random_uuid(),
    "professional_id" uuid,
    "date" date not null,
    "reason" text,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."unavailable_dates" enable row level security;

CREATE UNIQUE INDEX appointments_cancellation_token_key ON public.appointments USING btree (cancellation_token);

CREATE UNIQUE INDEX appointments_pkey ON public.appointments USING btree (id);

CREATE UNIQUE INDEX appointments_review_token_key ON public.appointments USING btree (review_token);

CREATE UNIQUE INDEX availability_pkey ON public.availability USING btree (id);

CREATE UNIQUE INDEX clients_email_key ON public.clients USING btree (email);

CREATE UNIQUE INDEX clients_pkey ON public.clients USING btree (id);

CREATE UNIQUE INDEX p_activo_pkey ON public.p_activo USING btree (id);

CREATE UNIQUE INDEX professionals_email_key ON public.professionals USING btree (email);

CREATE UNIQUE INDEX professionals_pkey ON public.professionals USING btree (id);

CREATE UNIQUE INDEX professionals_rut_key ON public.professionals USING btree (rut);

CREATE UNIQUE INDEX professionals_slug_key ON public.professionals USING btree (slug);

CREATE UNIQUE INDEX reviews_appointment_id_key ON public.reviews USING btree (appointment_id);

CREATE UNIQUE INDEX reviews_pkey ON public.reviews USING btree (id);

CREATE UNIQUE INDEX services_pkey ON public.services USING btree (id);

CREATE UNIQUE INDEX unavailable_dates_pkey ON public.unavailable_dates USING btree (id);

CREATE UNIQUE INDEX unavailable_dates_professional_id_date_key ON public.unavailable_dates USING btree (professional_id, date);

CREATE UNIQUE INDEX unique_active_appointments ON public.appointments USING btree (professional_id, start_time) WHERE (status <> ALL (ARRAY['cancelled_by_client'::text, 'cancelled_by_pro'::text]));

alter table "public"."appointments" add constraint "appointments_pkey" PRIMARY KEY using index "appointments_pkey";

alter table "public"."availability" add constraint "availability_pkey" PRIMARY KEY using index "availability_pkey";

alter table "public"."clients" add constraint "clients_pkey" PRIMARY KEY using index "clients_pkey";

alter table "public"."p_activo" add constraint "p_activo_pkey" PRIMARY KEY using index "p_activo_pkey";

alter table "public"."professionals" add constraint "professionals_pkey" PRIMARY KEY using index "professionals_pkey";

alter table "public"."reviews" add constraint "reviews_pkey" PRIMARY KEY using index "reviews_pkey";

alter table "public"."services" add constraint "services_pkey" PRIMARY KEY using index "services_pkey";

alter table "public"."unavailable_dates" add constraint "unavailable_dates_pkey" PRIMARY KEY using index "unavailable_dates_pkey";

alter table "public"."appointments" add constraint "appointments_cancellation_token_key" UNIQUE using index "appointments_cancellation_token_key";

alter table "public"."appointments" add constraint "appointments_client_id_fkey" FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE not valid;

alter table "public"."appointments" validate constraint "appointments_client_id_fkey";

alter table "public"."appointments" add constraint "appointments_professional_id_fkey" FOREIGN KEY (professional_id) REFERENCES public.professionals(id) ON DELETE CASCADE not valid;

alter table "public"."appointments" validate constraint "appointments_professional_id_fkey";

alter table "public"."appointments" add constraint "appointments_review_token_key" UNIQUE using index "appointments_review_token_key";

alter table "public"."appointments" add constraint "appointments_service_id_fkey" FOREIGN KEY (service_id) REFERENCES public.services(id) ON DELETE CASCADE not valid;

alter table "public"."appointments" validate constraint "appointments_service_id_fkey";

alter table "public"."appointments" add constraint "appointments_status_check" CHECK ((status = ANY (ARRAY['confirmed'::text, 'cancelled_by_pro'::text, 'completed'::text, 'cancelled_by_client'::text]))) not valid;

alter table "public"."appointments" validate constraint "appointments_status_check";

alter table "public"."availability" add constraint "availability_day_of_week_check" CHECK (((day_of_week >= 0) AND (day_of_week <= 6))) not valid;

alter table "public"."availability" validate constraint "availability_day_of_week_check";

alter table "public"."availability" add constraint "availability_professional_id_fkey" FOREIGN KEY (professional_id) REFERENCES public.professionals(id) ON DELETE CASCADE not valid;

alter table "public"."availability" validate constraint "availability_professional_id_fkey";

alter table "public"."clients" add constraint "clients_email_key" UNIQUE using index "clients_email_key";

alter table "public"."professionals" add constraint "professionals_email_key" UNIQUE using index "professionals_email_key";

alter table "public"."professionals" add constraint "professionals_rut_key" UNIQUE using index "professionals_rut_key";

alter table "public"."professionals" add constraint "professionals_slug_key" UNIQUE using index "professionals_slug_key";

alter table "public"."professionals" add constraint "professionals_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."professionals" validate constraint "professionals_user_id_fkey";

alter table "public"."reviews" add constraint "reviews_appointment_id_fkey" FOREIGN KEY (appointment_id) REFERENCES public.appointments(id) ON DELETE CASCADE not valid;

alter table "public"."reviews" validate constraint "reviews_appointment_id_fkey";

alter table "public"."reviews" add constraint "reviews_appointment_id_key" UNIQUE using index "reviews_appointment_id_key";

alter table "public"."reviews" add constraint "reviews_professional_id_fkey" FOREIGN KEY (professional_id) REFERENCES public.professionals(id) ON DELETE CASCADE not valid;

alter table "public"."reviews" validate constraint "reviews_professional_id_fkey";

alter table "public"."reviews" add constraint "reviews_rating_check" CHECK (((rating >= 1) AND (rating <= 5))) not valid;

alter table "public"."reviews" validate constraint "reviews_rating_check";

alter table "public"."services" add constraint "services_professional_id_fkey" FOREIGN KEY (professional_id) REFERENCES public.professionals(id) ON DELETE CASCADE not valid;

alter table "public"."services" validate constraint "services_professional_id_fkey";

alter table "public"."unavailable_dates" add constraint "unavailable_dates_professional_id_date_key" UNIQUE using index "unavailable_dates_professional_id_date_key";

alter table "public"."unavailable_dates" add constraint "unavailable_dates_professional_id_fkey" FOREIGN KEY (professional_id) REFERENCES public.professionals(id) ON DELETE CASCADE not valid;

alter table "public"."unavailable_dates" validate constraint "unavailable_dates_professional_id_fkey";

grant delete on table "public"."appointments" to "anon";

grant insert on table "public"."appointments" to "anon";

grant references on table "public"."appointments" to "anon";

grant select on table "public"."appointments" to "anon";

grant trigger on table "public"."appointments" to "anon";

grant truncate on table "public"."appointments" to "anon";

grant update on table "public"."appointments" to "anon";

grant delete on table "public"."appointments" to "authenticated";

grant insert on table "public"."appointments" to "authenticated";

grant references on table "public"."appointments" to "authenticated";

grant select on table "public"."appointments" to "authenticated";

grant trigger on table "public"."appointments" to "authenticated";

grant truncate on table "public"."appointments" to "authenticated";

grant update on table "public"."appointments" to "authenticated";

grant delete on table "public"."appointments" to "service_role";

grant insert on table "public"."appointments" to "service_role";

grant references on table "public"."appointments" to "service_role";

grant select on table "public"."appointments" to "service_role";

grant trigger on table "public"."appointments" to "service_role";

grant truncate on table "public"."appointments" to "service_role";

grant update on table "public"."appointments" to "service_role";

grant delete on table "public"."availability" to "anon";

grant insert on table "public"."availability" to "anon";

grant references on table "public"."availability" to "anon";

grant select on table "public"."availability" to "anon";

grant trigger on table "public"."availability" to "anon";

grant truncate on table "public"."availability" to "anon";

grant update on table "public"."availability" to "anon";

grant delete on table "public"."availability" to "authenticated";

grant insert on table "public"."availability" to "authenticated";

grant references on table "public"."availability" to "authenticated";

grant select on table "public"."availability" to "authenticated";

grant trigger on table "public"."availability" to "authenticated";

grant truncate on table "public"."availability" to "authenticated";

grant update on table "public"."availability" to "authenticated";

grant delete on table "public"."availability" to "service_role";

grant insert on table "public"."availability" to "service_role";

grant references on table "public"."availability" to "service_role";

grant select on table "public"."availability" to "service_role";

grant trigger on table "public"."availability" to "service_role";

grant truncate on table "public"."availability" to "service_role";

grant update on table "public"."availability" to "service_role";

grant delete on table "public"."clients" to "anon";

grant insert on table "public"."clients" to "anon";

grant references on table "public"."clients" to "anon";

grant select on table "public"."clients" to "anon";

grant trigger on table "public"."clients" to "anon";

grant truncate on table "public"."clients" to "anon";

grant update on table "public"."clients" to "anon";

grant delete on table "public"."clients" to "authenticated";

grant insert on table "public"."clients" to "authenticated";

grant references on table "public"."clients" to "authenticated";

grant select on table "public"."clients" to "authenticated";

grant trigger on table "public"."clients" to "authenticated";

grant truncate on table "public"."clients" to "authenticated";

grant update on table "public"."clients" to "authenticated";

grant delete on table "public"."clients" to "service_role";

grant insert on table "public"."clients" to "service_role";

grant references on table "public"."clients" to "service_role";

grant select on table "public"."clients" to "service_role";

grant trigger on table "public"."clients" to "service_role";

grant truncate on table "public"."clients" to "service_role";

grant update on table "public"."clients" to "service_role";

grant delete on table "public"."p_activo" to "anon";

grant insert on table "public"."p_activo" to "anon";

grant references on table "public"."p_activo" to "anon";

grant select on table "public"."p_activo" to "anon";

grant trigger on table "public"."p_activo" to "anon";

grant truncate on table "public"."p_activo" to "anon";

grant update on table "public"."p_activo" to "anon";

grant delete on table "public"."p_activo" to "authenticated";

grant insert on table "public"."p_activo" to "authenticated";

grant references on table "public"."p_activo" to "authenticated";

grant select on table "public"."p_activo" to "authenticated";

grant trigger on table "public"."p_activo" to "authenticated";

grant truncate on table "public"."p_activo" to "authenticated";

grant update on table "public"."p_activo" to "authenticated";

grant delete on table "public"."p_activo" to "service_role";

grant insert on table "public"."p_activo" to "service_role";

grant references on table "public"."p_activo" to "service_role";

grant select on table "public"."p_activo" to "service_role";

grant trigger on table "public"."p_activo" to "service_role";

grant truncate on table "public"."p_activo" to "service_role";

grant update on table "public"."p_activo" to "service_role";

grant delete on table "public"."professionals" to "anon";

grant insert on table "public"."professionals" to "anon";

grant references on table "public"."professionals" to "anon";

grant select on table "public"."professionals" to "anon";

grant trigger on table "public"."professionals" to "anon";

grant truncate on table "public"."professionals" to "anon";

grant update on table "public"."professionals" to "anon";

grant delete on table "public"."professionals" to "authenticated";

grant insert on table "public"."professionals" to "authenticated";

grant references on table "public"."professionals" to "authenticated";

grant select on table "public"."professionals" to "authenticated";

grant trigger on table "public"."professionals" to "authenticated";

grant truncate on table "public"."professionals" to "authenticated";

grant update on table "public"."professionals" to "authenticated";

grant delete on table "public"."professionals" to "service_role";

grant insert on table "public"."professionals" to "service_role";

grant references on table "public"."professionals" to "service_role";

grant select on table "public"."professionals" to "service_role";

grant trigger on table "public"."professionals" to "service_role";

grant truncate on table "public"."professionals" to "service_role";

grant update on table "public"."professionals" to "service_role";

grant delete on table "public"."reviews" to "anon";

grant insert on table "public"."reviews" to "anon";

grant references on table "public"."reviews" to "anon";

grant select on table "public"."reviews" to "anon";

grant trigger on table "public"."reviews" to "anon";

grant truncate on table "public"."reviews" to "anon";

grant update on table "public"."reviews" to "anon";

grant delete on table "public"."reviews" to "authenticated";

grant insert on table "public"."reviews" to "authenticated";

grant references on table "public"."reviews" to "authenticated";

grant select on table "public"."reviews" to "authenticated";

grant trigger on table "public"."reviews" to "authenticated";

grant truncate on table "public"."reviews" to "authenticated";

grant update on table "public"."reviews" to "authenticated";

grant delete on table "public"."reviews" to "service_role";

grant insert on table "public"."reviews" to "service_role";

grant references on table "public"."reviews" to "service_role";

grant select on table "public"."reviews" to "service_role";

grant trigger on table "public"."reviews" to "service_role";

grant truncate on table "public"."reviews" to "service_role";

grant update on table "public"."reviews" to "service_role";

grant delete on table "public"."services" to "anon";

grant insert on table "public"."services" to "anon";

grant references on table "public"."services" to "anon";

grant select on table "public"."services" to "anon";

grant trigger on table "public"."services" to "anon";

grant truncate on table "public"."services" to "anon";

grant update on table "public"."services" to "anon";

grant delete on table "public"."services" to "authenticated";

grant insert on table "public"."services" to "authenticated";

grant references on table "public"."services" to "authenticated";

grant select on table "public"."services" to "authenticated";

grant trigger on table "public"."services" to "authenticated";

grant truncate on table "public"."services" to "authenticated";

grant update on table "public"."services" to "authenticated";

grant delete on table "public"."services" to "service_role";

grant insert on table "public"."services" to "service_role";

grant references on table "public"."services" to "service_role";

grant select on table "public"."services" to "service_role";

grant trigger on table "public"."services" to "service_role";

grant truncate on table "public"."services" to "service_role";

grant update on table "public"."services" to "service_role";

grant delete on table "public"."unavailable_dates" to "anon";

grant insert on table "public"."unavailable_dates" to "anon";

grant references on table "public"."unavailable_dates" to "anon";

grant select on table "public"."unavailable_dates" to "anon";

grant trigger on table "public"."unavailable_dates" to "anon";

grant truncate on table "public"."unavailable_dates" to "anon";

grant update on table "public"."unavailable_dates" to "anon";

grant delete on table "public"."unavailable_dates" to "authenticated";

grant insert on table "public"."unavailable_dates" to "authenticated";

grant references on table "public"."unavailable_dates" to "authenticated";

grant select on table "public"."unavailable_dates" to "authenticated";

grant trigger on table "public"."unavailable_dates" to "authenticated";

grant truncate on table "public"."unavailable_dates" to "authenticated";

grant update on table "public"."unavailable_dates" to "authenticated";

grant delete on table "public"."unavailable_dates" to "service_role";

grant insert on table "public"."unavailable_dates" to "service_role";

grant references on table "public"."unavailable_dates" to "service_role";

grant select on table "public"."unavailable_dates" to "service_role";

grant trigger on table "public"."unavailable_dates" to "service_role";

grant truncate on table "public"."unavailable_dates" to "service_role";

grant update on table "public"."unavailable_dates" to "service_role";


  create policy "Allow appointment creation"
  on "public"."appointments"
  as permissive
  for insert
  to public
with check (true);



  create policy "Allow professional to update own appointments"
  on "public"."appointments"
  as permissive
  for update
  to public
using ((EXISTS ( SELECT 1
   FROM public.professionals
  WHERE ((professionals.id = appointments.professional_id) AND (professionals.user_id = auth.uid())))));



  create policy "Allow reading appointments"
  on "public"."appointments"
  as permissive
  for select
  to public
using (true);



  create policy "Anyone can view appointments"
  on "public"."appointments"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."appointments"
  as permissive
  for update
  to public
using (true);



  create policy "Professionals can update own appointments"
  on "public"."appointments"
  as permissive
  for update
  to public
using ((EXISTS ( SELECT 1
   FROM public.professionals
  WHERE ((professionals.id = appointments.professional_id) AND (professionals.user_id = auth.uid())))));



  create policy "Anyone can view availability"
  on "public"."availability"
  as permissive
  for select
  to public
using (true);



  create policy "Professionals can manage own availability"
  on "public"."availability"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.professionals
  WHERE ((professionals.id = availability.professional_id) AND (professionals.user_id = auth.uid())))));



  create policy "Allow client creation"
  on "public"."clients"
  as permissive
  for insert
  to public
with check (true);



  create policy "Allow reading clients"
  on "public"."clients"
  as permissive
  for select
  to public
using (true);



  create policy "Allow updating clients"
  on "public"."clients"
  as permissive
  for update
  to public
using (true);



  create policy "Anyone can update clients"
  on "public"."clients"
  as permissive
  for update
  to public
using (true);



  create policy "Anyone can view clients"
  on "public"."clients"
  as permissive
  for select
  to public
using (true);



  create policy "Allow own profile update"
  on "public"."professionals"
  as permissive
  for update
  to public
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "Allow professional creation"
  on "public"."professionals"
  as permissive
  for insert
  to public
with check (((auth.uid() = user_id) OR (auth.uid() IS NOT NULL)));



  create policy "Allow reading professionals for slug check"
  on "public"."professionals"
  as permissive
  for select
  to public
using (true);



  create policy "Users can update own profile"
  on "public"."professionals"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Users can view all professionals"
  on "public"."professionals"
  as permissive
  for select
  to public
using (true);



  create policy "Anyone can insert reviews"
  on "public"."reviews"
  as permissive
  for insert
  to public
with check (true);



  create policy "Anyone can view reviews"
  on "public"."reviews"
  as permissive
  for select
  to public
using (true);



  create policy "Anyone can view services"
  on "public"."services"
  as permissive
  for select
  to public
using (true);



  create policy "Professionals can manage own services"
  on "public"."services"
  as permissive
  for all
  to public
using ((EXISTS ( SELECT 1
   FROM public.professionals
  WHERE ((professionals.id = services.professional_id) AND (professionals.user_id = auth.uid())))));



  create policy "Professionals can manage their own unavailable dates"
  on "public"."unavailable_dates"
  as permissive
  for all
  to public
using ((auth.uid() IN ( SELECT professionals.user_id
   FROM public.professionals
  WHERE (professionals.id = unavailable_dates.professional_id))));



  create policy "Professional images are publicly accessible"
  on "storage"."objects"
  as permissive
  for select
  to public
using ((bucket_id = 'professional-images'::text));



  create policy "Users can delete their own professional images"
  on "storage"."objects"
  as permissive
  for delete
  to public
using (((bucket_id = 'professional-images'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));



  create policy "Users can update their own professional images"
  on "storage"."objects"
  as permissive
  for update
  to public
using (((bucket_id = 'professional-images'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));



  create policy "Users can upload their own professional images"
  on "storage"."objects"
  as permissive
  for insert
  to public
with check (((bucket_id = 'professional-images'::text) AND ((auth.uid())::text = (storage.foldername(name))[1])));



